  - name: Install docker dependencies 
    apt:
      pkg: 
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release
      - software-properties-common
      - gnupg-agent 
      update_cache: true 
  - name: Add docker gpg key 
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg 
      state: present 
  - name: Add docker APT Repo 
    apt_repository: 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower}} stable
      state: present 
  - name: Install docker engine 
    apt: 
      pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      update_cache: true 
  - name: Add ubuntu user to docker group 
    user: 
      name: ubuntu 
      groups: docker  
      append: yes
  - name: Add jenkins user to docker group
    user:
      name: jenkins
      comment: docker-jenk
      group: docker


  
  
  - name: Download docker-compose {{ docker_compose_version }}
    get_url:
      url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: ~/docker-compose
      mode: '+x'
  - name: Check docker-compose exists
    stat: path=~/docker-compose
    register: docker_compose
  - name: Move docker-compose to /usr/local/bin/docker-compose
    command: mv ~/docker-compose /usr/local/bin/docker-compose
    when: docker_compose.stat.exists
  
      

