- name: Install python3
  apt:
    pkg:
    - python3
    - python3-virtualenv
    - python3-dev
    - virtualenv
    state: present
    update_cache: true

- name: Install python-pip
  apt:
    pkg:
    - python3-pip
    - curl
    state: present
    update_cache: true
- name: pytest
  pip:
    name: pytest
- name: install nginx
  yum: name=nginx state=present

- name: install pip
  yum: name=python3-pip state=present 

- name: install flask
  pip: 
    name: flask 